require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
  Max: 30

RSpec/ExampleLength:
  Max: 10

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
