version: '3.9'
services:
  url_shortener_app:
    build: .
    container_name: url_shortener_app
    environment:
      - RAILS_ENV=production
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    # fixes and issue with Chrome running out of memory
    volumes:
      - /dev/shm:/dev/shm
